
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIVECASES CATEGORIES CHECKBOX CLOSEDATA CLOSEDIV CLOSEHEAD CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT DAILYDEATHS GARBAGE LINEAR LINEWIDTH NEWCASES OPENDATA OPENDIV OPENHEAD OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLE RECOVERED SPACE TOTALCASESstart : tabletable : TOTALCASES skiptag LINEAR skiptag CATEGORIES CONTENT skiptag LINEWIDTH CONTENT CONTENT CONTENT\n             | NEWCASES newcases\n             | ACTIVECASES skiptag LINEWIDTH CONTENT CONTENT CONTENT\n             | DAILYDEATHS skiptag CHECKBOX CONTENT CONTENT CONTENT\n             | RECOVERED skiptag LINEWIDTH CONTENT CONTENT CONTENTnewcases : skiptag CATEGORIES CONTENT skiptag CHECKBOX skiptag CHECKBOX CONTENT CONTENT CONTENTskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | SPACE skiptag\n               | emptyempty :content : CONTENT content\n               | empty'
    
_lr_action_items = {'TOTALCASES':([0,],[3,]),'NEWCASES':([0,],[4,]),'ACTIVECASES':([0,],[5,]),'DAILYDEATHS':([0,],[6,]),'RECOVERED':([0,],[7,]),'$end':([1,2,14,40,41,42,51,52,],[0,-1,-3,-4,-5,-6,-2,-7,]),'CONTENT':([3,4,5,6,7,9,10,11,12,19,24,25,26,27,29,30,31,32,33,35,36,37,38,39,45,46,47,48,49,50,],[9,9,9,9,9,9,9,9,9,9,29,30,31,32,9,35,36,37,38,40,41,42,9,9,47,48,49,50,51,52,]),'OPENHREF':([3,4,5,6,7,9,10,11,12,19,29,38,39,],[10,10,10,10,10,10,10,10,10,10,10,10,10,]),'CLOSEHREF':([3,4,5,6,7,9,10,11,12,19,29,38,39,],[11,11,11,11,11,11,11,11,11,11,11,11,11,]),'SPACE':([3,4,5,6,7,9,10,11,12,19,29,38,39,],[12,12,12,12,12,12,12,12,12,12,12,12,12,]),'LINEAR':([3,8,9,10,11,12,13,20,21,22,23,],[-13,19,-13,-13,-13,-13,-12,-8,-9,-10,-11,]),'CATEGORIES':([4,9,10,11,12,13,15,19,20,21,22,23,28,],[-13,-13,-13,-13,-13,-12,24,-13,-8,-9,-10,-11,33,]),'LINEWIDTH':([5,7,9,10,11,12,13,16,18,20,21,22,23,38,43,],[-13,-13,-13,-13,-13,-13,-12,25,27,-8,-9,-10,-11,-13,45,]),'CHECKBOX':([6,9,10,11,12,13,17,20,21,22,23,29,34,39,44,],[-13,-13,-13,-13,-13,-12,26,-8,-9,-10,-11,-13,39,-13,46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,4,5,6,7,9,10,11,12,19,29,38,39,],[8,15,16,17,18,20,21,22,23,28,34,43,44,]),'empty':([3,4,5,6,7,9,10,11,12,19,29,38,39,],[13,13,13,13,13,13,13,13,13,13,13,13,13,]),'newcases':([4,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','task3.py',134),
  ('table -> TOTALCASES skiptag LINEAR skiptag CATEGORIES CONTENT skiptag LINEWIDTH CONTENT CONTENT CONTENT','table',11,'p_table','task3.py',138),
  ('table -> NEWCASES newcases','table',2,'p_table','task3.py',139),
  ('table -> ACTIVECASES skiptag LINEWIDTH CONTENT CONTENT CONTENT','table',6,'p_table','task3.py',140),
  ('table -> DAILYDEATHS skiptag CHECKBOX CONTENT CONTENT CONTENT','table',6,'p_table','task3.py',141),
  ('table -> RECOVERED skiptag LINEWIDTH CONTENT CONTENT CONTENT','table',6,'p_table','task3.py',142),
  ('newcases -> skiptag CATEGORIES CONTENT skiptag CHECKBOX skiptag CHECKBOX CONTENT CONTENT CONTENT','newcases',10,'p_newcases','task3.py',156),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','task3.py',161),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','task3.py',162),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','task3.py',163),
  ('skiptag -> SPACE skiptag','skiptag',2,'p_skiptag','task3.py',164),
  ('skiptag -> empty','skiptag',1,'p_skiptag','task3.py',165),
  ('empty -> <empty>','empty',0,'p_empty','task3.py',168),
  ('content -> CONTENT content','content',2,'p_content','task3.py',172),
  ('content -> empty','content',1,'p_content','task3.py',173),
]
